import { useEffect, useMemo, useRef, useState } from 'react';
import { api } from '../services/api';

const initialChecks = [['Display affinity', 'Clean', 'ok'], ['Tab focus', 'Focused', 'ok'], ['Clipboard', 'Normal', 'ok']];
const now = () => new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });

export function useMeeting() {
  const [identity, setIdentity] = useState(null); const [session, setSession] = useState(null); const [form, setForm] = useState({ sessionId: 'tech-interview-live-892', participantName: '', role: 'candidate', passcode: '' });
  const [error, setError] = useState(''); const [joining, setJoining] = useState(false); const [threats, setThreats] = useState([]); const [checks, setChecks] = useState(initialChecks); const [logs, setLogs] = useState([]); const [elapsed, setElapsed] = useState(0); const [media, setMedia] = useState({ mic: true, cam: true, share: false }); const [stream, setStream] = useState(null); const threatKey = useRef('');
  const addLog = (message, level = 'system') => setLogs(old => [...old, { id: crypto.randomUUID(), at: now(), message, level }]);
  const trust = threats.length ? 35 : 100; const initials = useMemo(() => (session?.participantName || identity?.name || '?').split(' ').map(word => word[0]).join('').slice(0, 2).toUpperCase(), [session, identity]);
  useEffect(() => { api.currentUser().then(data => { if (data.authenticated) { setIdentity(data.user); setForm(old => ({ ...old, participantName: old.participantName || data.user.name || '' })); } }).catch(() => {}); }, []);
  useEffect(() => { if (!session) return; const timer = setInterval(() => setElapsed(value => value + 1), 1000); const source = new EventSource('/api/telemetry/stream'); source.onmessage = event => { try { const data = JSON.parse(event.data); const detected = data.threats || []; const key = detected.map(item => item.hwnd || item.pid).join(','); setThreats(detected); setChecks(old => old.map((check, index) => index === 0 ? [check[0], data.hasThreat ? 'Detected' : 'Clean', data.hasThreat ? 'fail' : 'ok'] : check)); if (key && key !== threatKey.current) addLog(`Threat detected: ${detected[0].title || detected[0].path || 'unknown window'}`, 'alert'); threatKey.current = key; } catch {} }; return () => { clearInterval(timer); source.close(); }; }, [session]);
  useEffect(() => { if (!session) return; const focus = () => { const lost = document.hidden; setChecks(old => old.map((check, index) => index === 1 ? [check[0], lost ? 'Lost' : 'Focused', lost ? 'fail' : 'ok'] : check)); if (lost) addLog('Tab focus lost.', 'warn'); }; const paste = event => { const text = event.clipboardData?.getData('text') || ''; if (text.length > 30) { setChecks(old => old.map((check, index) => index === 2 ? [check[0], 'Bulk paste', 'fail'] : check)); addLog(`Large paste detected (${text.length} characters).`, 'warn'); } }; document.addEventListener('visibilitychange', focus); document.addEventListener('paste', paste); return () => { document.removeEventListener('visibilitychange', focus); document.removeEventListener('paste', paste); }; }, [session]);
  useEffect(() => () => stream?.getTracks().forEach(track => track.stop()), [stream]);
  const join = async event => { event.preventDefault(); setError(''); setJoining(true); try { const data = await api.joinSession(form); setSession({ ...data, authProvider: identity ? 'Google Workspace + meeting access' : 'Meeting access' }); setElapsed(0); addLog('Session started. Integrity monitoring is active.'); try { setStream(await navigator.mediaDevices.getUserMedia({ video: true, audio: true })); } catch { addLog('Camera or microphone access was not granted.', 'warn'); } } catch (err) { setError(err.message); } finally { setJoining(false); } };
  const googleSignIn = async () => { try { if ((await api.googleStatus()).enabled) window.location.assign('/api/auth/google'); else setError('Google sign-in has not been configured by the workspace administrator.'); } catch { setError('Google sign-in is currently unavailable.'); } };
  const toggleMedia = kind => { if (!stream) return; const active = !media[kind]; setMedia(old => ({ ...old, [kind]: active })); (kind === 'mic' ? stream.getAudioTracks() : stream.getVideoTracks()).forEach(track => { track.enabled = active; }); };
  const toggleShare = async () => { if (media.share) return setMedia(old => ({ ...old, share: false })); try { const share = await navigator.mediaDevices.getDisplayMedia({ video: true }); share.getVideoTracks()[0].onended = () => setMedia(old => ({ ...old, share: false })); setMedia(old => ({ ...old, share: true })); addLog('Screen sharing started.'); } catch {} };
  const exportAudit = async () => { const payload = { sessionTitle: session.title, sessionId: session.sessionId, candidate: session.participantName, role: session.role, authentication: session.authProvider, timestamp: new Date().toISOString(), finalTrustScore: `${trust}%`, activeThreatsDetected: threats, incidentLogs: logs }; await api.saveAudit(payload).catch(() => {}); const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })); Object.assign(document.createElement('a'), { href: url, download: `securemeet-audit-${Date.now()}.json` }).click(); URL.revokeObjectURL(url); addLog('Audit report exported.'); };
  return { identity, session, form, setForm, error, joining, join, googleSignIn, threats, checks, logs, setLogs, elapsed, media, stream, initials, trust, toggleMedia, toggleShare, exportAudit };
}
