import { useRef, useEffect, useState } from 'react';
import { SecurityPanel } from '../security/SecurityPanel';

const elapsed = seconds => [Math.floor(seconds / 3600), Math.floor(seconds / 60) % 60, seconds % 60].map(value => String(value).padStart(2, '0')).join(':');
const Control = ({ children, label, active, danger, onClick }) => <button aria-label={label} title={label} className={`control ${active ? 'active' : ''} ${danger ? 'danger' : ''}`} onClick={onClick}>{children}</button>;
function VideoTile({ name, initials, stream, muted, threatened }) { const video = useRef(null); useEffect(() => { if (video.current) video.current.srcObject = stream || null; }, [stream]); return <article className={`video-tile ${threatened ? 'threatened' : ''}`}>{stream ? <video ref={video} autoPlay playsInline muted /> : <div className="avatar">{initials}</div>}<footer><span>{name}</span><small>{muted ? 'Mic off' : 'Mic on'}</small></footer></article>; }

export function MeetingWorkspace({ meeting }) {
  const [guardOpen, setGuardOpen] = useState(true); const [tab, setTab] = useState('detection'); const threat = meeting.threats[0];
  const leave = () => { if (window.confirm('Leave this secure session?')) window.location.reload(); };
  return <main className="workspace"><header className="topbar"><div className="brand"><b>S</b> SecureMeet <span>/ {meeting.session.sessionId}</span></div><div className="timer">{elapsed(meeting.elapsed)}</div><button className={`trust ${threat ? 'alert' : ''}`} onClick={() => setGuardOpen(true)}><i /> {threat ? 'Attention' : 'Secure'} <strong>{meeting.trust}%</strong></button></header><section className="content"><div className="stage"><div className="stage-label"><span className="live-dot" /> LIVE SESSION <small>{meeting.session.title}</small></div><div className="video-grid"><VideoTile name={meeting.session.participantName} initials={meeting.initials} stream={meeting.stream} muted={!meeting.media.mic} threatened={Boolean(threat)} /><VideoTile name="Interviewer" initials="I" /></div></div>{guardOpen && <SecurityPanel tab={tab} setTab={setTab} threat={threat} meeting={meeting} onClose={() => setGuardOpen(false)} />}</section><footer className="controls"><span>{meeting.session.participantName} · {meeting.session.role}</span><div><Control label="Microphone" active={!meeting.media.mic} onClick={() => meeting.toggleMedia('mic')}>M</Control><Control label="Camera" active={!meeting.media.cam} onClick={() => meeting.toggleMedia('cam')}>C</Control><Control label="Share screen" active={meeting.media.share} onClick={meeting.toggleShare}>S</Control><Control label="Leave session" danger onClick={leave}>X</Control></div><button className="panel-toggle" onClick={() => setGuardOpen(value => !value)}>{guardOpen ? 'Hide guard' : 'Open guard'}</button></footer></main>;
}
